const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

// Deploys Chargings to whatever network you pass, prints the address, and writes the
// address + ABI to app/src/config.js so the frontend is wired up automatically.
async function main() {
  const Chargings = await hre.ethers.getContractFactory("Chargings");
  const chargings = await Chargings.deploy();
  await chargings.waitForDeployment();

  const address = await chargings.getAddress();
  console.log(`Chargings deployed to: ${address}`);

  // pull the ABI straight out of the fresh Hardhat artifact
  const artifact = await hre.artifacts.readArtifact("Chargings");

  const configPath = path.join(__dirname, "..", "..", "app", "src", "config.js");
  const contents =
    `// AUTO-GENERATED by contracts/scripts/deploy.js on each deploy.\n` +
    `// Holds the deployed contract address + ABI so every component imports the same wiring.\n` +
    `export const CONTRACT_ADDRESS = "${address}";\n\n` +
    `// Local Hardhat network (npx hardhat node). Point MetaMask here.\n` +
    `export const LOCAL_CHAIN = {\n` +
    `  chainId: "0x7a69", // 31337\n` +
    `  chainName: "Hardhat Local",\n` +
    `  rpcUrls: ["http://127.0.0.1:8545"],\n` +
    `  nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },\n` +
    `};\n\n` +
    `export const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};\n`;

  fs.mkdirSync(path.dirname(configPath), { recursive: true });
  fs.writeFileSync(configPath, contents);
  console.log(`Wrote address + ABI -> ${configPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
